### ISSUE TITLE
IncompatibleClassChangeError with v0.3.0 and jvm sdk v1.2.0

### ISSUE THREAD

**Issue by exx-trost** [commercetools/commercetools-jvm-sdk-spring-add-ons#4]
We get the following error in commercetools-jvm-sdk-spring-add-ons after upgrading the jvm sdk to version 1.2.0:

`java.lang.IncompatibleClassChangeError: Found interface io.sphere.sdk.queries.PagedQueryResult, but class was expected
at com.commercetools.sdk.jvm.spring.batch.item.SortByIdQueryItemReader.queryNewElements(SortByIdQueryItemReader.java:58)
at com.commercetools.sdk.jvm.spring.batch.item.SortByIdQueryItemReader.read(SortByIdQueryItemReader.java:41)
        [...]`

This seems to be a bug due to not aligning this package with the new sdk version. Could you please fix this?

**Comment by schleichardt** [comment]
The version 0.3.0 was compiled against 1.0.0-RC1, I fixed the `IncompatibleClassChangeError` with releasing version 0.4.0 which is compiled for JVM SDK 1.2.0.

Since we won't introduce breaking changes like for `PagedQueryResult` in the release candidate phase, newer JVM SDK versions should still work with 0.4.0.

**Comment by exx-trost** [comment]
Thanks!
